use_frameworks!

target 'Styley_Example' do
  pod 'Styley', :path => '../'

  target 'Styley_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
